### ISSUE TITLE
Error on installation

### ISSUE THREAD

**Issue by andirey** [s-u/jpeg#3]
Hi!
I tried to install package as a part of "ggmap" installation:
devtools::install_github("s-u/jpeg")
==
And get the following errors

* installing *source* package ‘jpeg’ ...
** libs
gcc -std=gnu99 -I/usr/share/R/include -DNDEBUG      -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c read.c -o read.o
In file included from read.c:1:0:
rjcommon.h:11:21: fatal error: jpeglib.h: No such file or directory
compilation terminated.
/usr/lib/R/etc/Makeconf:159: recipe for target 'read.o' failed
make: *** [read.o] Error 1
ERROR: compilation failed for package ‘jpeg’
* removing ‘/home/andrii/R/x86_64-pc-lin

Will be glad to know how to fix it

**Comment by s-u** [comment]
You are missing the jpeg library - you may need something like `apt-get install libjpeg-dev` or similar depending on your OS.
