### ISSUE TITLE
Installation error: ld: library not found for -ljpeg

### ISSUE THREAD

**Issue by ibagur** [s-u/jpeg#7]
Hi, I am trying to install by compiling from source on R 4.0.3 on BigSur 11.2 and get this error:

```
ld: library not found for -ljpeg
clang-11: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [qpdf.so] Error 1
ERROR: compilation failed for package `‘qpdf’```
```

I have libjpeg 9d installed via Homebrew. I tried to reinstall and re-start R with no success. No matter what, the error persists. Any suggestions? Thanks

**Comment by s-u** [comment]
1) Please ask the relevant package author - in the above output that would be `qpdf`.  2) include full output since you omitted all important information such as the flags used. 3) if you use Homebrew, direct reports to Homebrew
